config/routes.rb
VerboiceBillingSystem::Application.routes.draw do

  root 'traffics#index'
  get 'sign_in', to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  delete 'sign_out', to: 'sessions#destroy'

  resources :billings, only: [:index] do
    collection do
      get 'filter_error'
      get 'detail'
    end
  end

  resources :call_rates
  resources :traffics
  resources :channels, only: [:index] do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :instances
  resources :quota_histories
  resources :quotas do
    resources :quota_histories, shallow: true
  end

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  validates :name, :url, :end_point, presence: true
  validates_uniqueness_of :name, :url, :end_point
  validates_format_of :url, :end_point, with: URI.regexp

  MINIMUM = 1 # must be at least one
  has_many :call_rates
  has_many :quotas
  has_many :quota_histories
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  # GET /instances
  def index
    @instances = Instance.all.page(params[:page])
  end

  # GEt /instances/new
  def new
    @instance = Instance.new
  end

  # POST /instances
  def create
    @instance = Instance.new instance_params

    if(@instance.save)
      flash[:success] =  'Instance has been created'
      redirect_to instances_path
    else
      flash.now[:error] = 'Failed to create instance'
      render :new
    end
  end

  def edit
    @instance = Instance.find(params[:id])
  end

  def update
    @instance = Instance.find(params[:id])
    
    if @instance.update_attributes(instance_params)
      flash[:success] =  'Instance has been updated'
      redirect_to instances_path
    else
      flash.now[:error] = 'Failed to update instance'
      render :edit
    end
  end

  def destroy
    @instance = Instance.find(params[:id])
    
    if Instance.count > Instance::MINIMUM
      if @instance.destroy
        flash[:success] =  "Instance '#{@instance.name}' has been deleted"
        redirect_to instances_path
      else
        flash[:error] = 'Failed to delete instance'
        redirect_to instances_path
      end
    else
      flash[:error] = 'Instance must be at least one'
      redirect_to instances_path
    end
  end

  private

  def instance_params
    params.require(:instance).permit(:name, :url, :end_point)
  end

end

app/views/instances/_form.html.erb
<%= simple_form_for(@instance, html: {class: 'form-horizontal' }) do |form| %>
  <%= form.input :name, required: true %>
  <%= form.input :url, required: true, as: :url %>
  <%= form.input :end_point, required: true %>
  
  <%= submit_row do %>
    <%= form.submit "Save", class: 'btn btn-primary btn-submit' %>
  <% end %>
<% end %>

app/views/instances/edit.html.erb
<%= page_title_with "Edit Instance" %>
<%= action_bar "Edit Instance" %>
<%= render 'form' %>

app/views/instances/index.html.erb
<%= page_title_with "List of instances" %>
<%= action_bar "List of instances" do %>
  <%= new_button "New", new_instance_path() %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Url</th>
      <th>End point</th>
      <th>Action</th>
    </tr>
  </thead>
  
  <% @instances.each_with_index do |instance, index| %>
  <tr>
    <td><%= link_to page_index_for(@instances, index), edit_instance_path(instance) %></td>
    <td><%= instance.name %></td>
    <td><%= instance.url %></td>
    <td><%= instance.end_point %></td>
    <td class='action-2'>
        <%= edit_button 'Edit', edit_instance_path(instance),  class: 'btn btn-primary' %>
        <%= delete_button 'Delete', instance_path(instance), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this instance" } %>
    </td>
  </tr>
  <% end %>
</table>

<%= paginate @instances, :theme => 'twitter-bootstrap' %>

app/views/instances/new.html.erb
<%= page_title_with "New Instance" %>
<%= action_bar "New Instance" %>
<%= render 'form' %>