config/routes.rb
VerboiceBillingSystem::Application.routes.draw do

  root 'traffics#index'
  get 'sign_in', to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  delete 'sign_out', to: 'sessions#destroy'

  resources :billings, only: [:index] do
    collection do
      get 'filter_error'
      get 'detail'
    end
  end

  resources :call_rates
  resources :traffics
  resources :channels, only: [:index] do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :instances
  resources :quota_histories
  resources :quotas do
    resources :quota_histories, shallow: true
  end

end

app/models/quota.rb
class Quota < ActiveRecord::Base
  self.table_name = 'quotas'
  validates :account_id, :channel_id, :total, presence: true
  validates :total, numericality:  { greater_than: 0}
  validates :channel_id, uniqueness: {scope: :instance_id}

  before_save :set_call_blocked
  belongs_to  :instance

  has_many :quota_histories

  extend ByInstance

  def enabled_as_text
    self.enabled ? 'Yes' : 'No'
  end

  def block_if_reached_as_text
    self.block_if_reached ? 'Block' : 'Allow'
  end

  def self.as_enabled
    where(['enabled = ?', true])
  end

  def current_percentage
    self.used * 100 / self.total
  end

  def warning?
    # remaining quota less than percentate_condition
    (100 - self.current_percentage) < self.percentage_condition
  end

  def blocked_as_text
    self.blocked ?  'Blocked' : 'OK'
  end

  def is_reached?
    self.used >= self.total
  end

  private
  def set_call_blocked
    if self.is_reached?
      self.blocked = 1 if self.block_if_reached
      self.blocked = 0 if !self.block_if_reached
    else
      self.blocked = 0
    end
  end

end

app/controllers/quotas_controller.rb
class QuotasController < ApplicationController
  def index
    @quotas = Quota.by_instance(instance).page(params[:page])
  end

  def new
    @quota = Quota.new
  end

  def create
    @quota = Quota.new filter_params

    @quota.from_date = Time.zone.now.beginning_of_month
    @quota.to_date  = Time.zone.now.end_of_month

    if @quota.save
      Service::ChannelQuota.save_quota(@quota)

      flash[:success] = "Quota has been created"
      redirect_to quotas_path()
    else
      flash.now[:error] = "Failed to create quota"
      render :new
    end
  end

  def edit
    @quota = Quota.find params[:id]
  end

  def update
    @quota = Quota.find params[:id]

    options = {
      enabled: @quota.enabled,
      blocked: @quota.blocked
    }

    if @quota.update_attributes filter_params
      Service::ChannelQuota.update_quota(@quota, options)
      flash[:success] = "Quota has been updated successfully"
      redirect_to quotas_path()
    else
      flash.now[:error] = "Failed to update quota"
      render :edit
    end
  end

  def destroy
    begin
      @quota = Quota.find params[:id]
      channel_quota_id = @quota.channel_quota_id
      @quota.destroy
      Service::ChannelQuota.destroy(channel_quota_id)
      flash[:success]  = "Quota has been removed successfully"
    rescue Exception => e
      flash.now[:error] = e.message
    end
    redirect_to quotas_path
  end

  private

  def filter_params
    attributes = params.require(:quota).permit(:account_id, :account_email, :channel_name, :channel_id, :total,
     :used, :alert_email, :block_if_reached, :enabled, :percentage_condition)
    with_instance(attributes)
  end
end

app/views/quotas/_form.html.erb
<% url = @quota.new_record? ? quotas_path() : quota_path(@quota) %>
<%= simple_form_for( @quota, url: url , html: {class: 'form-horizontal' }) do |form| %>

 <%= form.input :account_id, collection: Service::Account.collection ,
                             prompt: "--- Select account ---",
                             input_html: { id: 'account_id_field'}
                             %>

 <%= form.input :channel_id, collection: Service::Channel.collection(@quota.account_id) ,
                             prompt: "--- Select channel ---",
                             input_html: { id: 'channel_id_field'}

                             %>
 <%= form.input :channel_name, as: 'hidden', input_html: {id: 'channel_name_field'} %>
 <%= form.input :account_email, as: 'hidden', input_html: {id: 'account_email_field'} %>

 <%= form.input :total, label: 'Monthly quota (USD)' %>
 <%#= form.input :used %>
 <table>
 <tr>
  <td> <%= form.input :alert_email, label: 'Alert to email ' %></td>
  <td> <%= form.input :percentage_condition, 
                      label: 'when remaining quota less than (%)',
                      input_html: {style: 'width: 40px;'} %></td>
 </tr>
 </table>


 <%= form.input :block_if_reached, label: 'block channel when run out of quota' %>

 <%#= form.input :from_date, input_html: {class: 'datepicker'}, as: :string %>
 <%#= form.input :to_date, input_html: {class: 'datepicker'}, as: :string %>

 <%= form.input :enabled , label: 'Enable quota', as: :boolean %>

  <%= submit_row do %>
    <%= form.submit "Save", class: 'btn btn-primary btn-submit' %>
  <% end %>

<% end %>

app/views/quotas/edit.html.erb
<%= page_title_with "Edit Quota" %>
<%= action_bar "Edit Quota" %>
<%= render 'form' %>

app/views/quotas/index.html.erb
<%= page_title_with "List of Quotas" %>
<%= action_bar "List of Quotas" do %>
  <%= new_button "New", new_quota_path() %>
<% end %>

<table class="table table-striped">
  <thead>  
      <tr>
        <th>No</th>
        <th>Account</th>
        <th>Channel</th>
        <th>Total Quota</th>
        <th>Used Quota</th>
        <th>Alert Condition</th>
        <th>Alert email</th>

        <th>Over quota</th>
        <th>Enable Quota</th>
        <th>Channel Status</th>
        <th>Action</th>
      </tr>
  </thead>

  <tbody>
    <% @quotas.each_with_index do |quota, index| %>
      <tr>
        <td><%= link_to page_index_for(@quotas, index), edit_quota_path(quota) %></td>
        <td><%= quota.account_email%></td>
        <td><%= quota.channel_name%></td>
        <td><%= number_to_currency(quota.total, unit: '$', precision: 2) %></td>
        <td><%= number_to_currency(quota.used, unit: '$', precision: 2) %></td>
        <td><%= quota.percentage_condition%> % </td>

        <td class='td-expandable' title="<%= quota.alert_email %>" >
           <%= truncate(quota.alert_email, length: 30) %>
        </td>

        <td><%= quota.block_if_reached_as_text %></td>
        <td><%= quota.enabled_as_text %></td>
        <td><%= quota.blocked_as_text %></td>

        <td class='action-2'>
          <%= edit_button 'Edit', edit_quota_path(quota),  class: 'btn btn-primary' %>

          <%= delete_button 'Delete', quota_path(quota), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this quota" } %>
          <%#= edit_button 'Histories', quota_quota_histories_path(quota),  class: 'btn btn-primary' %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @quotas, :theme => 'twitter-bootstrap' %>

app/views/quotas/new.html.erb
<%= page_title_with "New Quota" %>
<%= action_bar "New Quota" %>
<%= render 'form' %>