config/routes.rb
VerboiceBillingSystem::Application.routes.draw do

  root 'traffics#index'
  get 'sign_in', to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  delete 'sign_out', to: 'sessions#destroy'

  resources :billings, only: [:index] do
    collection do
      get 'filter_error'
      get 'detail'
    end
  end

  resources :call_rates
  resources :traffics
  resources :channels, only: [:index] do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :instances
  resources :quota_histories
  resources :quotas do
    resources :quota_histories, shallow: true
  end

end

app/models/call_rate.rb
class CallRate < ActiveRecord::Base
  validates :account_id, :channel_id, :incoming_rate, :outgoing_rate, :prefix, presence: true
  validates :incoming_rate, :outgoing_rate, :round_rate, numericality:  { greater_than_or_equal_to: 0}
  validates :channel_id, uniqueness: {scope: [:prefix, :instance_id] }

  validate :prefix_no_white_space
  validate :unique_prefix
  attr_accessor :address

  DEFAULT_ROUND = 0

  belongs_to :instance
  extend ByInstance
  
  def unique_prefix
    call_rates = CallRate.where(['channel_id=:channel_id', channel_id: self.channel_id])

    call_rates.each do |call_rate|
      if call_rate != self && call_rate.has_prefix?(self.prefix)
        errors.add :prefix, "already exists for channel #{self.channel_name}"
      end
    end
  end

  def prefix_no_white_space
    if self.prefix.present? && self.prefix.include?(" ")
      errors.add :prefix, "white space is not allowed. please clean it up"
    end
  end

  def has_prefix? p
    prefixes = p.split(',')
    current_prefixes = self.prefix.split(",")

    prefixes.each do |temp_pref|
      return true if current_prefixes.include?(temp_pref)
    end
    return false
  end

  def has_address? address
    prefixes = self.prefix.split(",")
    prefixes.each do |p|
      return true if address.start_with?(p)
    end
    false
  end

  def cost_for call_log
    rate_cost = rate_for call_log

    if(self.round_rate == CallRate::DEFAULT_ROUND)
      call_rate_per_second = (rate_cost / 60).to_f
      cost = (call_log.duration.nil? ? 0 : call_log.duration) * call_rate_per_second
    else
      call_rate_per_round = (self.round_rate * rate_cost) / 60
      cost = (call_log.duration.to_f / self.round_rate).ceil * call_rate_per_round
    end
    
    cost
  end 

  def rate_for call_log
    call_log.incoming? ? self.incoming_rate : self.outgoing_rate
  end     

end

app/controllers/call_rates_controller.rb
class CallRatesController < ApplicationController
  def index
    @call_rates = CallRate.by_instance(instance)
    @call_rates = @call_rates.by_account(params[:account_id]) if params[:account_id].present?
    @call_rates = @call_rates.by_channel(params[:channel_id]) if params[:channel_id].present?

    @call_rates = @call_rates.page(params[:page])
  end
  
  def new
    @call_rate = CallRate.new
  end

  def create
    @call_rate = CallRate.new filter_params

    if(@call_rate.save)
      flash[:success] =  'Call rate has been created'
      redirect_to call_rates_path
    else
      flash.now[:error] = 'Failed to create call rate'
      render :new
    end
  end

  def edit
    @call_rate = CallRate.find params[:id]
  end

  def update
    @call_rate = CallRate.find params[:id]
    if(@call_rate.update_attributes(filter_params))
      flash[:success] = "Call rate has been udated"
      redirect_to call_rates_path()
    else
      flash.now[:error] = "Failed to update call rate"
      render :edit  
    end
  end

  def destroy
    begin
      @call_rate = CallRate.find params[:id]
      @call_rate.destroy
      flash[:success] = 'Call rate has been deleleted'
    rescue Exception => e
      flash[:error] = e.message
    end

    redirect_to call_rates_path
  end

  def filter_params
    attributes = params.require(:call_rate).permit(:account_id, :account_email, :channel_name, :channel_id, :prefix,
     :incoming_rate, :outgoing_rate, :note, :round_rate)
    with_instance(attributes)
  end


end

app/views/call_rates/_form.html.erb
<%= simple_form_for(@call_rate, html: {class: 'form-horizontal' }) do |form| %>

 <%= form.input :account_id, collection: Service::Account.collection,
                             prompt: "--- Select account ---",
                             input_html: {id: "account_id_field" }

                             %>
 <%= form.input :channel_id, collection: Service::Channel.collection(@call_rate.account_id),
                             prompt: "--- Select channel ---",
                             input_html: {id: "channel_id_field"}
                             %>

 <%= form.input :channel_name, as: 'hidden', input_html: {id: "channel_name_field"} %>
 <%= form.input :account_email, as: 'hidden', input_html: {id: "account_email_field"} %>

 <%= form.input :prefix %>
 <%= form.input :round_rate, label: 'Round up (second)' %>
 <%= form.input :incoming_rate %>
 <%= form.input :outgoing_rate %>
 <%= form.input :note %>

  <%= submit_row do %>
    <%= form.submit "Save", class: 'btn btn-primary btn-submit' %>
  <% end %>
  
<% end %>

app/views/call_rates/_search_form.html.erb
<%= form_tag call_rates_path, :method => 'get' do %>
  <div class="left">
    <%= select_tag "account_id", options_for_select(Service::Account.collection, params[:account_id]), prompt: "--- All account ---" %>
    <%= select_tag "channel_id", options_for_select(Service::Channel.collection(params[:account_id]), params[:channel_id]), prompt: "--- All channel ---" %>
  </div>
  <div><%= submit_tag "Search", class: 'btn btn-primary btn-submit' %></div>
<% end %>

app/views/call_rates/edit.html.erb
<%= page_title_with "Edit Call rate" %>
<%= action_bar "Edit Call rate" %>
<%= render 'form' %>

app/views/call_rates/index.html.erb
<%= render 'search_form' %>

<%= page_title_with "List of Call rates" %>
<%= action_bar "List of Call rates" do %>
  <%= new_button "New", new_call_rate_path() %>
<% end %>

<table class="table table-striped">
  <thead>  
      <tr>
        <th>No</th>
        <th>Account</th>
        <th>Channel</th>
        <th>Prefix</th>
        <th>Round</th>
        <th>Incoming Rate</th>
        <th>Outcoming Rate</th>
        <th>Note</th>
        <th>Action</th>    
      </tr>
  </thead>

  <tbody>
    <% @call_rates.each_with_index do |call_rate, index| %>
      <tr>
        <td><%=link_to page_index_for(@call_rates, index), edit_call_rate_path(call_rate) %></td>
        <td><%=call_rate.account_email%></td>
        <td><%=call_rate.channel_name%></td>
        <td><%=call_rate.prefix%></td>
        <td><%=call_rate.round_rate%></td>
        <td><%=call_rate.incoming_rate%></td>
        <td><%=call_rate.outgoing_rate%></td>

        <td class='td-expandable' title='<%= call_rate.note %>'>
            <%=truncate(call_rate.note, length: 30)%>
        </td>

        <td class='action-2'>
          <%= edit_button 'Edit', edit_call_rate_path(call_rate),  class: 'btn btn-primary' %>
          <%= delete_button 'Delete', call_rate_path(call_rate), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this call rate" } %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @call_rates, :theme => 'twitter-bootstrap' %>

app/views/call_rates/new.html.erb
<%= page_title_with "New Call rate" %>
<%= action_bar "New Call rate" %>
<%= render 'form' %>