config/routes.rb
VerboiceBillingSystem::Application.routes.draw do

  root 'traffics#index'
  get 'sign_in', to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  delete 'sign_out', to: 'sessions#destroy'

  resources :billings, only: [:index] do
    collection do
      get 'filter_error'
      get 'detail'
    end
  end

  resources :call_rates
  resources :traffics
  resources :channels, only: [:index] do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :instances
  resources :quota_histories
  resources :quotas do
    resources :quota_histories, shallow: true
  end

end

app/views/layouts/_config.html.erb
<script>
  window.config = {
    host: '<%= root_url %>'
  }
</script>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class='alert alert-danger fade in'>
    <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='copyright'>
  <p>&copy; Copyright 

    <a href='http://www.instedd.org' style='text-decoration:none;'>
      <img src='http://www.ilabsoutheastasia.org/wp-content/themes/instedd_v3/images/favicon.ico' />
      InSTEDD
    </a>
  </p>
</footer>

app/views/layouts/_login_bar.html.erb
<% if current_access.present? %>

  

  <ul class="nav pull-right">
    <li class="dropdown">
      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
        <%= "#{instance.try(:name)} ( #{current_access[:email]} )" %><b class="caret"></b>
      </a>
      <ul class="dropdown-menu">

        <li>
          <%= link_to 'Sign out', sign_out_path, 
                      method: 'delete', 
                      data: { confirm: 'Are you sure to sign out' } %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      
      <%= link_to ENV['APP_NAME'], root_path, class: 'brand' %>
      <div class="container nav-collapse">
        <ul class="nav">
          <li class="<%= active('traffics') %>" ><%= link_to "Traffics", traffics_path %></li>
          <li class="<%= active('call_rates') %>" ><%= link_to "Call Rates", call_rates_path %></li>
          <li class="<%= active('quotas') %>" ><%= link_to "Call Quota", quotas_path %></li>
          <li class="<%= active('quota_histories') %>" ><%= link_to "Quota Histories", quota_histories_path %></li>
          <li class="<%= active('channels') %>" ><%= link_to "Channels", channels_path %></li>
          <li class="<%= active('instances') %>" ><%= link_to "Instances", instances_path %></li>
        </ul>
        <%= render 'layouts/login_bar' %>
        
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <%= render 'layouts/config' %>
  </head>
  <body>
    <%= render 'layouts/nav_bar' %>
    <div class="container body">

      <div class="row">
        <div class="span12">
          <p><%= bootstrap_flash %></p>
          <%= yield %>
        </div>
      </div><!--/row-->

      <%= render 'layouts/footer' %>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!--Info -->
    <title><%= "Error :: #{@app_name}" %></title>

    <!--Styling -->
    <style>
      
		html {
			height: 100%;
			background: #fff asset_url("custom_error_pages/bg.png") bottom repeat-x;
		}
		
		body {
			font-family: Helvetica, Arial, Sans-Serif;
			font-size: 14px;
		}
		.error_container {
			display: block;
			margin: auto;
			margin: 10% auto 0 auto;
			width: 30%;
		}
		
		.error_container .error {
			display: block;
			text-align: center;
		}
		
		.error_container .error img.alert {
			display: block;
			margin: 0 auto 25px auto;
		}
		
		.error_container .message > * {
			display: block;
		}
		
		.error_container .message strong {
			font-weight: bold;
			font-size: 1.5em;
			color: #f00;
			margin: 15px 0 0;
		}

		.error_container .message span {
			margin: 5px auto 0;
			font-size: 0.75em;
			color: #606060;
		}
		
		.error_container .contact {
			display: block;
			text-align: center;
			margin: 20px 0 0 0;
		}
		
		.error_container .contact a {
			display: inline-block;
			margin: 0 -1px; /* For inline block & ERB - HAML removes whitespace; ERB does now - http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_removal__and_ */
			opacity: 0.4;
			transition: opacity 0.15s ease;
		}

		.error_container .contact a img {
			display: block;
			width: 38px;
			height: 38px;
		}
		
		.error_container .contact a:hover {
			opacity: 0.8;
		}

    </style>
  </head>
  
  <!--Body -->
  <body>
    <div class="error_container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <%= link_to ENV['APP_NAME'], root_path, class: 'brand' %>

          <div class="container nav-collapse">
            <ul class="nav">
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <%= render 'layouts/footer' %>

    </div> <!-- /container -->

  </body>
</html>